@startuml
!define webActor(x)  actor x <<akka>>  

actor "App User" as user
participant WebApp as web

webActor(UserData)
webActor(CarHistory)
webActor(CarData)

user->web:GetPage
web->UserData:GetUserData
web<-UserData : UserData
web--> CarData : getCarTechnicalDetails
web--> CarHistory  :getCarServiceHistory
web-> user : BasePage
CarHistory  --> web : CarServiceHistory
web -->user : CarServiceHistory(SignalR)
CarData-->web:CarTechnicalDetails
web -->user : CarTechnicalDetails(SignalR)

@enduml
