@startuml
!define PLANTUML_HOME D:\dev\LocalLibrary\PlantUmlDrawings
!include PLANTUML_HOME\definitions.plantuml

actor "App\nUser" as user
participant WebApp as web

webActor(UserData)
webActor(CarHistory)
webActor(CarData)

user->web:GetPage
web->UserData:GetUserData
web<-UserData : UserData
web--> CarData : getCarTechnicalDetails
web--> CarHistory  :getCarServiceHistory
web-> user : BasePage
CarHistory  --> web : CarServiceHistory
web -->user : CarServiceHistory(SignalR)
CarData-->web:CarTechnicalDetails
web -->user : CarTechnicalDetails(SignalR)

skinparam actor {
    backgroundColor webActor Green
    backgroundColor "App User" Green
}

@enduml
