@startuml
!define PLANTUML_HOME D:\dev\LocalLibrary\PlantUmlDrawings
!include PLANTUML_HOME\definitions.plantuml

package application <<Cloud System>> {
database mongoDB <<imageStorage>> as mongo
database sqlLike <<dataStorage>>
webActor(webServer)
webActor(internalServices)

webServer <-down- internalServices
webServer -down-> internalServices

internalServices <-up- sqlLike
internalServices -up-> sqlLike
internalServices -> mongo
internalServices <- mongo
}

package mobileDevices <<Android, Apple, Windows>> {
garageMechanicUser <-> webServer 
garageManagerUser <-> webServer 
carOwnerUser <-> webServer 
}

package browsers{
garageManagersUser <-up-> webServer 
carOwnersUser <-up-> webServer 
}

@enduml