@startuml
!define PLANTUML_HOME D:\dev\LocalLibrary\PlantUmlDrawings
!include PLANTUML_HOME\definitions.plantuml
'left to right direction

title Work In progress
cloud "========\ncloud\n========"{
database "Event Store\nhttp://docs.geteventstore.com/" as eventStore {
 frame "actor events" as actorEvents {
    [persistence]
    [rollbacks]
    [events]
  } 

  frame "application events" as applicationEvents {
    [security]
    [exceptions]
    [logging]
    [stats]
  }
 }

database "MongoDB" {
 frame "images" {
    [serviceImages]
    [userImages]
  }

  frame "objects" {
    [reports]
    [configurations]
    [mobileAppBackups]
    [upload\ndownload\npackages]
  }
}


database "Sql Database\n any relational database fromy MySql to whatever suit" as sqlDatabase {
 frame "transactions" {
    [buy/sell]
    [invoices] 	
    [etc...]
  }

  frame "userData" {
    [userData]
    [securityStuff]

  }
}


 
cloud "akka Cluster" {
node webWorkersManagement{
  }  
  webWorkersManagement <--> WebWorkers

package "WebWorkers" {
frame "api(s)"{
[carStatisitcs]
[carPartsData]
[registrationPlatesApi]
[partsShopApi]
[garagesContactsApi]
}
}

  node eventHandlers{
  [r]  
  }

 actorEvents -[#0000FF]-> eventHandlers

  node persistenceProviders{
  [d]
  [dd]
  }

  persistenceProviders -> eventStore
  persistenceProviders <-> MongoDB




} 



}


@enduml